<const_decl> ::= "const" <assignment>;
<assignment> ::= <identifier> "=" <expression>;

(* Words *)

<lowercase> ::= [a-z];
<uppercase> ::= [A-Z];
<identifier_char> ::= <lowercase>|<uppercase>|"_";
<identifier> ::= <identifier_char>|<identifier><identifier_char>;

(* Numeric Expressions*)

<numeric_expression> ::= <numeric_literal>|<identifier>|<calculation>;
<calculation> ::= <subtraction>|<division>|<addition>|<multiplication>|<modulo>;
<subtraction> ::= <numeric_expression>"-"<numeric_expression>;
<addition> ::= <numeric_expression>"+"<numeric_expression>;
<multiplication> ::= <numeric_expression>"*"<numeric_expression>;
<division> ::= <numeric_expression>"/"<numeric_expression>;
<modulo> ::=  <numeric_expression>"%"<numeric_expression>;

(* Number Literals *)

<numeric_literal> ::= <int>|<float>;
<float> ::= "-"<ufloat>|<ufloat>;
<ufloat> ::= <uint>"."<uint>;
<int> ::= <uint>|"-"<uint>;
<uint> ::= <digit>|<nonzero><digits>;
<digits> ::= <digit>|<digits><digit>;
<digit> ::= "0"|<nonzero>;
<nonzero> ::= [1-9];
